config/routes.rb
Falcon::Application.routes.draw do
  get "our_products/products"

  get "contact_us/contact"

  get "about_us/about"

  devise_for :admins
  devise_for :admins do
    get '/admins/sign_out' => 'devise/sessions#destroy'
  end

  resources :product_tags

  resources :tags

  resources :products

  root :to => 'products#index'

 namespace "admin" do
   resources :products
   root :to => 'products#index'
 end

end

app/models/product_tag.rb
class ProductTag < ActiveRecord::Base
  attr_accessible :product_id, :tag_id
end

app/controllers/product_tags_controller.rb
class ProductTagsController < ApplicationController
  # GET /product_tags
  # GET /product_tags.json
  before_filter :authenticate_admin!, :except=>[:index,:show]
  def index
    @product_tags = ProductTag.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @product_tags }
    end
  end

  # GET /product_tags/1
  # GET /product_tags/1.json
  def show
    @product_tag = ProductTag.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product_tag }
    end
  end

  # GET /product_tags/new
  # GET /product_tags/new.json
  def new
    @product_tag = ProductTag.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product_tag }
    end
  end

  # GET /product_tags/1/edit
  def edit
    @product_tag = ProductTag.find(params[:id])
  end

  # POST /product_tags
  # POST /product_tags.json
  def create
    @product_tag = ProductTag.new(params[:product_tag])

    respond_to do |format|
      if @product_tag.save
        format.html { redirect_to @product_tag, notice: 'Product tag was successfully created.' }
        format.json { render json: @product_tag, status: :created, location: @product_tag }
      else
        format.html { render action: "new" }
        format.json { render json: @product_tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /product_tags/1
  # PUT /product_tags/1.json
  def update
    @product_tag = ProductTag.find(params[:id])

    respond_to do |format|
      if @product_tag.update_attributes(params[:product_tag])
        format.html { redirect_to @product_tag, notice: 'Product tag was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product_tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_tags/1
  # DELETE /product_tags/1.json
  def destroy
    @product_tag = ProductTag.find(params[:id])
    @product_tag.destroy

    respond_to do |format|
      format.html { redirect_to product_tags_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/product_tags_helper.rb
module ProductTagsHelper
end

app/views/product_tags/_form.html.erb
<%= form_for(@product_tag) do |f| %>
  <% if @product_tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product_tag.errors.count, "error") %> prohibited this product_tag from being saved:</h2>

      <ul>
      <% @product_tag.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tag_id %><br />
    <%= f.number_field :tag_id %>
  </div>
  <div class="field">
    <%= f.label :product_id %><br />
    <%= f.number_field :product_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/product_tags/edit.html.erb
<h1>Editing product_tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @product_tag %> |
<%= link_to 'Back', product_tags_path %>

app/views/product_tags/index.html.erb
<h1>Listing product_tags</h1>

<table>
  <tr>
    <th>Tag</th>
    <th>Product</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @product_tags.each do |product_tag| %>
  <tr>
    <td><%= product_tag.tag_id %></td>
    <td><%= product_tag.product_id %></td>
    <td><%= link_to 'Show', product_tag %></td>
    <td><%= link_to 'Edit', edit_product_tag_path(product_tag) %></td>
    <td><%= link_to 'Destroy', product_tag, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product tag', new_product_tag_path %>

app/views/product_tags/new.html.erb
<h1>New product_tag</h1>

<%= render 'form' %>

<%= link_to 'Back', product_tags_path %>

app/views/product_tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Tag:</b>
  <%= @product_tag.tag_id %>
</p>

<p>
  <b>Product:</b>
  <%= @product_tag.product_id %>
</p>


<%= link_to 'Edit', edit_product_tag_path(@product_tag) %> |
<%= link_to 'Back', product_tags_path %>