config/routes.rb
Falcon::Application.routes.draw do
  get "our_products/products"

  get "contact_us/contact"

  get "about_us/about"

  devise_for :admins
  devise_for :admins do
    get '/admins/sign_out' => 'devise/sessions#destroy'
  end

  resources :product_tags

  resources :tags

  resources :products

  root :to => 'products#index'

 namespace "admin" do
   resources :products
   root :to => 'products#index'
 end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable, :rememberable, :registerable:,recoverable
  devise :database_authenticatable, 
          :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/asset.rb
class Asset < ActiveRecord::Base
   attr_accessible :title, :body, :image
  belongs_to :product
  has_attached_file :image, :styles=>{:small => "211x120#"}
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessible :resource
  belongs_to :product
    has_attached_file :resource, :styles => {:small => "211x120"}
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :description, :title, :user_id, :assets_attributes
  validates :title, :description, :presence => true
 
  has_many :assets, :dependent=> :destroy
  accepts_nested_attributes_for :assets, :allow_destroy=>true
end

app/models/product_tag.rb
class ProductTag < ActiveRecord::Base
  attr_accessible :product_id, :tag_id
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name, :user_id
end

app/controllers/about_us_controller.rb
class AboutUsController < ApplicationController
  def about
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contact_us_controller.rb
class ContactUsController < ApplicationController
  def contact
  end
end

app/controllers/ourproducts_controller.rb
class OurproductsController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  
  before_filter :authenticate_admin!, :except=>[:index,:show]
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new
    5.times {@product.assets.build}
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
    5.times {@product.assets.build}
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  # GET /tags
  # GET /tags.json
  before_filter :authenticate_admin!, :except=>[:index,:show]


  def index
    @tags = Tag.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tags }
    end
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
    @tag = Tag.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tag }
    end
  end

  # GET /tags/new
  # GET /tags/new.json
  def new
    @tag = Tag.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tag }
    end
  end

  # GET /tags/1/edit
  def edit
    @tag = Tag.find(params[:id])
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(params[:tag])

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render json: @tag, status: :created, location: @tag }
      else
        format.html { render action: "new" }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tags/1
  # PUT /tags/1.json
  def update
    @tag = Tag.find(params[:id])

    respond_to do |format|
      if @tag.update_attributes(params[:tag])
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to tags_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/about_us_helper.rb
module AboutUsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_us_helper.rb
module ContactUsHelper
end

app/helpers/our_products_helper.rb
module OurProductsHelper
end

app/helpers/product_tags_helper.rb
module ProductTagsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE HTML>
<html lang="en-US">
<head>
<meta charset="UTF-8">
<title>FalconBD</title>
<%= stylesheet_link_tag "style","folks", :media => "all" %>


<!--[if IE 7]>
<link rel="stylesheet" type="text/css" href="style/css/ie7.css" media="all" />
<![endif]-->

<%= javascript_include_tag('jquery-1.5.min','jquery.cycle.all.min','ddsmoothmenu','scripts')%>

<script type="text/javascript">
$(function() {
      if ($('#sliderholder-cycle').length) {
      // timeouts per slide (in seconds) 
      var timeouts = [150,390,25]; 
      function calculateTimeout(currElement, nextElement, opts, isForward) { 
          var index = opts.currSlide; 
          return timeouts[index] * 1000;
      }
      jQuery('#sliderholder-cycle').cycle({
        fx: 'fade',
        pager: '.slidernav',
        prev:    '.sliderprev',
            next:    '.slidernext',
        speed: 1000,
        timeoutFn: calculateTimeout,
        pagerEvent: 'click',
          pauseOnPagerHover: true,
          cleartype: 1
});
      jQuery('#sliderholder-cycle').css("display", "block");
      jQuery('.slidernav').css("display", "block");
      
      }
}); 
</script>
</head>
<body>
<div id="container"> 
  <!-- Begin Header Wrapper -->
  <div id="page-top">
    <div id="header-wrapper"> 
      <!-- Begin Header -->
      <div id="header">
        <div id="logo"><a href="index.html"><%=image_tag('logo.png', :alt=>"Falcon")   %></a></div>
        <!-- Logo --> 
        <!-- Begin Menu -->
        <div id="menu-wrapper">
          <div id="smoothmenu1" class="ddsmoothmenu">
            <ul>
              <li><a href="index.html" class="selected">Home</a>
              
              </li>
              <li><a href="#">Our Products</a>
                <ul>
                  <li><a href="#">Papper Products</a></li>
                  <li><a href="#">Label Products</a></li>
                  <li><a href="#">Button</a></li>
                  <li><a href="#">Others</a></li>
                </ul>
              </li>
              
              
              <li><a href="page-tabs-toggle.html">Features</a>
                <ul>
                  <li><a href="#">Tabs &amp; Toggle</a></li>
                  <li><a href="#">Carousel</a></li>
                  <li><a href="#">News</a></li>
                  <li><a href="#">Services</a></li>
                  <li><a href="#">Custom Page</a></li>
                  <li><a href="#">Buttons</a></li>
                  <li><a href="#">Columns &amp; Tables</a></li>
                </ul>
              </li>
              <li><a href="#">About Us</a>
                            </li>

              <li><a href="contact.html">Contact Us</a></li>
            </ul>
          </div>
        </div>
        <!-- End Menu --> 
      </div>
      <!-- End Header --> 
    </div>
  </div>
  <!-- End Header Wrapper --> 
  
  <div id="wrapper"><!--Beggin Common Wrapper -->


  <!-- Begin Slider -->
  <div id="cycle-wrapper">
    <div id="sliderholder-cycle"><%=image_tag('slider-1.jpg', :width=>"960",:height=>"380")   %> 
      <%=image_tag('slider-2.jpg', :width=>"960",:height=>"380")   %> 
      <%=image_tag('slider-3.jpg', :width=>"960",:height=>"380")   %>
      <%=image_tag('slider-4.jpg', :width=>"960",:height=>"380")   %> 
        </div>
    <ul class="slidernav">
    </ul>
    <div class="sliderdir"> <a href="#"><span class="sliderprev">Prev</span></a> <a href="#"><span class="slidernext">Next</span></a> </div>
  </div>
  <!-- End Slider --> 
  
  <!-- Begin Wrapper -->
  <div id="wrapper"> 
    
    <!-- Begin Intro -->
    <div class="intro">
      <h1>Falcon Bangladesh. One of the largest Garment Accessories company in Bangladesh. </h1>
    </div>
    <!-- End Intro --> 
    
    <!-- Begin About -->
    <div id="about">
      

    <% @products.each do |product| %>
<div class="one-fourth">
  <div style="float:right;">
    <a href="#">
  <%= image_tag product.photo.url(:small) %></a>
   <h4> <%= product.title %></h4>
  <p><%= product.description %></p>
  </div>  
</div>
  <% end %>
    </div>
    <!-- End About --> 
    
  </div>
  
  <!-- End Wrapper -->
</div> <!-- End Common Wrapper-->

  <div class="clearfix"></div>
  <div class="push"></div>
</div>

<!-- Begin Footer -->
<div id="footer-wrapper">
  <div id="footer">
    <div id="footer-content"> 
      
      <!-- Begin Copyright -->
      <div id="copyright">
        <p>© Copyright 2012 Falcon | E-SolutionPark (SHUVO)</p>
      </div>
      <!-- End Copyright --> 
      
      <!-- Begin Social Icons -->
      <div id="socials">
        <ul>
          <li><a href="#"><img src="style/images/icon-rss.png" alt="" /></a></li>
          <li><a href="#"><img src="style/images/icon-twitter.png" alt="" /></a></li>
          <li><a href="#"><img src="style/images/icon-dribble.png" alt="" /></a></li>
          <li><a href="#"><img src="style/images/icon-tumblr.png" alt="" /></a></li>
          <li><a href="#"><img src="style/images/icon-flickr.png" alt="" /></a></li>
          <li><a href="#"><img src="style/images/icon-facebook.png" alt="" /></a></li>
        </ul>
      </div>
      <!-- End Social Icons --> 
      
    </div>
  </div>
</div>
<!-- End Footer -->
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE HTML>
<html lang="en-US">
<head>
<meta charset="UTF-8">
<title>FalconBD</title>
<%= stylesheet_link_tag "style","folks", :media => "all" %>


<!--[if IE 7]>
<link rel="stylesheet" type="text/css" href="style/css/ie7.css" media="all" />
<![endif]-->

<%= javascript_include_tag('jquery-1.5.min','jquery.cycle.all.min','ddsmoothmenu','scripts')%>

<script type="text/javascript">
$(function() {
      if ($('#sliderholder-cycle').length) {
      // timeouts per slide (in seconds) 
      var timeouts = [150,390,25]; 
      function calculateTimeout(currElement, nextElement, opts, isForward) { 
          var index = opts.currSlide; 
          return timeouts[index] * 1000;
      }
      jQuery('#sliderholder-cycle').cycle({
        fx: 'fade',
        pager: '.slidernav',
        prev:    '.sliderprev',
            next:    '.slidernext',
        speed: 1000,
        timeoutFn: calculateTimeout,
        pagerEvent: 'click',
          pauseOnPagerHover: true,
          cleartype: 1
});
      jQuery('#sliderholder-cycle').css("display", "block");
      jQuery('.slidernav').css("display", "block");
      
      }
}); 
</script>
</head>
<body>
  <div id="container"> 
  <!-- Begin Header Wrapper -->
  <div id="page-top">
    <div id="header-wrapper"> 
      <!-- Begin Header -->
      <div id="header">
        <div id="logo"><%=image_tag('logo1.png', :alt=>"Falcon")   %></div>
        <!-- Logo --> 
        <!-- Begin Menu -->
        <div id="menu-wrapper">
          <div id="smoothmenu1" class="ddsmoothmenu">
            <ul>
              <li><%=link_to("Home", root_path)%>
              
              </li>
              <li><%=link_to("Our Products", our_products_products_path)%>
                
              </li>
              
              
              
              <li><%=link_to("About Us", about_us_about_path)%>
                            </li>

              <li><%=link_to("Contact Us", contact_us_contact_path)%></li>
            </ul>
          </div>
        </div>
        <!-- End Menu --> 
      </div>
      <!-- End Header --> 
    </div>
  </div>
  <!-- End Header Wrapper --> 



<div id="wrapper"><!--Beggin Common Wrapper -->


    

        
          
               
              <%= yield %>
            
            
       

    </div> <!-- End of Common Wrapper -->

    
    <div class="clearfix"></div>
  
</div>

<!-- Begin Footer -->
<div id="footer-wrapper">
  <div id="footer">
    <div id="footer-content"> 
      
      <!-- Begin Copyright -->
      <div id="copyright">
        <p>© Copyright 2012 Falcon
      </div>
      <!-- End Copyright --> 
      
      <!-- Begin Social Icons -->
    <!--   <div id="socials">
        <ul>
          <li><a href="#"><img src="style/images/icon-rss.png" alt="" /></a></li>
          <li><a href="#"><img src="style/images/icon-twitter.png" alt="" /></a></li>
          <li><a href="#"><img src="style/images/icon-dribble.png" alt="" /></a></li>
          <li><a href="#"><img src="style/images/icon-tumblr.png" alt="" /></a></li>
          <li><a href="#"><img src="style/images/icon-flickr.png" alt="" /></a></li>
          <li><a href="#"><img src="style/images/icon-facebook.png" alt="" /></a></li>
        </ul>
      </div> -->
      <!-- End Social Icons --> 
      
    </div>
  </div>
</div>
<!-- End Footer -->


    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>